#!/bin/bash
# Setup passwordless sudo for nginx deployment
# Run this ONCE on the production server to enable automated TLS fix deployment

echo "Setting up passwordless sudo for nginx commands..."
echo ""
echo "This requires root/sudo access. Instructions:"
echo ""
echo "1. SSH to production:"
echo "   ssh deployuser@77.68.79.252"
echo ""
echo "2. Add deployuser to sudoers for nginx commands:"
echo "   sudo visudo"
echo ""
echo "3. Add this line at the end of the file:"
echo "   deployuser ALL=(ALL) NOPASSWD: /usr/sbin/nginx, /bin/cp, /bin/rm, /bin/systemctl"
echo ""
echo "4. Save and exit (Ctrl+X in nano, then :wq in vi)"
echo ""
echo "5. Test it works (should NOT prompt for password):"
echo "   sudo nginx -t"
echo ""
echo "6. Run deployment script:"
echo "   bash scripts/deploy-tls-security-fix.sh"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "QUICK SETUP (if you prefer automated):"
echo ""
echo "SSH to server and paste:"
echo 'echo "deployuser ALL=(ALL) NOPASSWD: /usr/sbin/nginx, /bin/cp, /bin/rm, /bin/systemctl" | sudo tee -a /etc/sudoers.d/deployuser-nginx'
echo ""
echo "Then verify:"
echo "sudo nginx -t  # Should work without password"
echo ""
